CREATE TABLE AwayTeam(
   Match_Day_Number INTEGER NOT NULL REFERENCES Matches(Match_Day_Number) 
  ,Home_Team        VARCHAR NOT NULL REFERENCES Matches(Home_Team )
  ,AwayTeam         VARCHAR NOT NULL
  ,PRIMARY KEY(Match_Day_Number, Home_Team)
);
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Man United','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Bournemouth','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Fulham','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Huddersfield','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Newcastle','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Watford','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Wolves','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Arsenal','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Liverpool','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (1,'Southampton','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Cardiff','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Chelsea','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Everton','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Leicester','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Tottenham','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'West Ham','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Brighton','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Burnley','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Man City','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (2,'Crystal Palace','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Arsenal','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Bournemouth','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Huddersfield','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Liverpool','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Southampton','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Wolves','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Fulham','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Newcastle','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Watford','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (3,'Man United','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Brighton','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Chelsea','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Crystal Palace','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Everton','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Leicester','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Man City','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'West Ham','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Burnley','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Cardiff','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (4,'Watford','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Bournemouth','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Chelsea','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Huddersfield','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Man City','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Newcastle','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Tottenham','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Watford','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Everton','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Wolves','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (5,'Southampton','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Brighton','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Burnley','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Cardiff','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Crystal Palace','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Fulham','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Leicester','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Liverpool','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Man United','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'Arsenal','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (6,'West Ham','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Arsenal','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Chelsea','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Everton','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Huddersfield','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Man City','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Newcastle','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'West Ham','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Wolves','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Cardiff','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (7,'Bournemouth','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Brighton','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Burnley','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Crystal Palace','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Leicester','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Man United','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Tottenham','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Watford','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Fulham','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Liverpool','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (8,'Southampton','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Bournemouth','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Cardiff','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Chelsea','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Huddersfield','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Man City','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Newcastle','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'West Ham','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Wolves','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Everton','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (9,'Arsenal','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Brighton','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Fulham','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Leicester','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Liverpool','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Southampton','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Watford','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Burnley','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Crystal Palace','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Man United','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (10,'Tottenham','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Arsenal','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Bournemouth','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Cardiff','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Everton','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Newcastle','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'West Ham','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Wolves','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Chelsea','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Man City','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (11,'Huddersfield','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Cardiff','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Crystal Palace','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Huddersfield','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Leicester','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Newcastle','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Southampton','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Arsenal','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Chelsea','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Liverpool','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (12,'Man City','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Brighton','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Everton','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Fulham','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Man United','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Tottenham','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Watford','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'West Ham','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Bournemouth','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Wolves','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (13,'Burnley','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Cardiff','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Crystal Palace','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Huddersfield','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Leicester','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Man City','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Newcastle','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Southampton','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Arsenal','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Chelsea','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (14,'Liverpool','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Bournemouth','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Brighton','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Watford','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'West Ham','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Burnley','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Everton','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Fulham','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Man United','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Tottenham','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (15,'Wolves','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Arsenal','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Bournemouth','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Burnley','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Cardiff','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Chelsea','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Leicester','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Man United','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'West Ham','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Newcastle','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (16,'Everton','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Crystal Palace','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Fulham','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Huddersfield','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Man City','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Tottenham','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Watford','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Wolves','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Brighton','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Liverpool','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (17,'Southampton','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Wolves','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Arsenal','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Bournemouth','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Cardiff','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Chelsea','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Huddersfield','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Man City','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Newcastle','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'West Ham','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (18,'Everton','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Brighton','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Burnley','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Crystal Palace','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Fulham','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Leicester','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Liverpool','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Man United','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Tottenham','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Watford','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (19,'Southampton','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Brighton','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Fulham','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Leicester','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Liverpool','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Tottenham','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Watford','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Burnley','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Crystal Palace','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Man United','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (20,'Southampton','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Arsenal','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Cardiff','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Everton','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Bournemouth','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Chelsea','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Huddersfield','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Newcastle','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'West Ham','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Wolves','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (21,'Man City','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Brighton','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Burnley','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Cardiff','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Chelsea','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Crystal Palace','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Leicester','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'West Ham','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Everton','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Tottenham','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (22,'Man City','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Arsenal','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Bournemouth','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Liverpool','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Man United','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Newcastle','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Southampton','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Watford','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Wolves','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Fulham','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (23,'Huddersfield','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Arsenal','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Fulham','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Huddersfield','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Man United','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Newcastle','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Wolves','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Bournemouth','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Liverpool','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Southampton','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (24,'Tottenham','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Brighton','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Burnley','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Cardiff','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Chelsea','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Crystal Palace','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Everton','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Tottenham','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Leicester','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'Man City','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (25,'West Ham','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Everton','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Brighton','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Crystal Palace','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Fulham','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Huddersfield','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Liverpool','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Southampton','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Watford','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Man City','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Tottenham','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (26,'Wolves','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Cardiff','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'West Ham','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Bournemouth','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Burnley','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Leicester','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Newcastle','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Arsenal','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (27,'Man United','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Cardiff','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Huddersfield','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Leicester','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Newcastle','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Arsenal','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Chelsea','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Crystal Palace','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Liverpool','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Man City','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (28,'Southampton','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Bournemouth','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Brighton','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Burnley','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Man United','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Tottenham','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'West Ham','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Wolves','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Everton','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Fulham','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (29,'Watford','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Cardiff','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Crystal Palace','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Huddersfield','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Leicester','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Man City','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Newcastle','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Southampton','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Arsenal','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Chelsea','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (30,'Liverpool','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (31,'Bournemouth','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (31,'Burnley','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (31,'West Ham','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (31,'Everton','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (31,'Fulham','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Brighton','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Burnley','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Crystal Palace','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Fulham','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Leicester','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Man United','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'West Ham','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Cardiff','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Liverpool','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Arsenal','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Watford','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Wolves','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Chelsea','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Man City','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (32,'Tottenham','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (33,'Southampton','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (33,'Bournemouth','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (33,'Huddersfield','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (33,'Newcastle','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (33,'Everton','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (33,'Chelsea','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Leicester','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Brighton','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Burnley','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Fulham','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Man United','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Southampton','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Tottenham','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Crystal Palace','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Liverpool','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Watford','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (34,'Brighton','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Bournemouth','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Huddersfield','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Man City','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Newcastle','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'West Ham','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Wolves','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Arsenal','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Cardiff','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Everton','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Chelsea','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Tottenham','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Watford','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Man United','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (35,'Wolves','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Liverpool','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Brighton','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Crystal Palace','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Fulham','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Southampton','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Tottenham','West Ham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Watford','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Burnley','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Leicester','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (36,'Man United','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Everton','Burnley');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Bournemouth','Tottenham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Cardiff','Crystal Palace');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Newcastle','Liverpool');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'West Ham','Southampton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Wolves','Fulham');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Arsenal','Brighton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Chelsea','Watford');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Huddersfield','Man United');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (37,'Man City','Leicester');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Brighton','Man City');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Burnley','Arsenal');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Crystal Palace','Bournemouth');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Fulham','Newcastle');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Leicester','Chelsea');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Liverpool','Wolves');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Man United','Cardiff');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Southampton','Huddersfield');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Tottenham','Everton');
INSERT INTO AwayTeam(Match_Day_Number,Home_Team,AwayTeam) VALUES (38,'Watford','West Ham');
