CREATE TABLE City(
   city                          VARCHAR NOT NULL PRIMARY KEY
  ,Population                    INTEGER  NOT NULL
  ,Number_of_Premier_league_team INTEGER  NOT NULL
);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('London',7556900,6);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Liverpool',864122,2);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Manchester',395515,2);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Leicester',508916,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cardiff',447287,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wolverhampton',252791,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Southampton',246201,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newcastle',192382,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bournemouth',163600,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Burnley',149422,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Huddersfield',149017,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Brighton',139001,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Watford',125707,1);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Birmingham',984333,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Nottingham',729977,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sheffield',685368,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bristol',617280,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Glasgow',591620,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Edinburgh',464990,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Leeds',455123,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stoke-on-Trent',372775,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Coventry',359262,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sunderland',335415,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Birkenhead',325264,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Islington',319143,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Reading',318014,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kingston upon Hull',314018,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Preston',313332,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newport',306844,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Swansea',300352,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bradford',299310,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Southend-on-Sea',295310,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Belfast',274770,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Derby',270468,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Plymouth',260203,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Luton',258018,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('City of Westminster',247614,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Blackpool',239409,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Milton Keynes',229941,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bexley',228000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Northampton',215963,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Archway',215667,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Norwich',213166,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dudley',199059,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Aberdeen',196670,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Portsmouth',194150,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sutton',187600,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Swindon',185609,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Crawley',180508,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ipswich',178835,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wigan',175405,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Croydon',173314,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Walsall',172141,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Mansfield',171958,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Oxford',171380,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Warrington',165456,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Slough',163777,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Peterborough',163379,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cambridge',158434,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Doncaster',158141,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('York',153717,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Poole',150092,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Gloucester',150053,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Telford',147980,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dundee',147710,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Blackburn',146521,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Basildon',144859,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Middlesbrough',142707,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bolton',141331,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stockport',139052,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('West Bromwich',135618,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Grimsby',134160,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hastings',133422,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('High Wycombe',133204,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Saint Peters',125370,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Burton upon Trent',122199,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Colchester',121859,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Eastbourne',118219,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Exeter',117763,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rotherham',117618,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cheltenham',116447,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lincoln',114879,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chesterfield',113057,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chelmsford',111511,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Mendip',110000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dagenham',108368,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Basingstoke',107642,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Maidstone',107627,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sutton Coldfield',107030,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bedford',106940,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Oldham',104782,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Enfield Town',103970,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Woking',103932,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('St Helens',102555,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Worcester',101659,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Gillingham',101187,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Becontree',100000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Worthing',99110,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rochdale',97550,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Solihull',96267,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Royal Leamington Spa',95172,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Romford',95000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bath',94782,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Harlow',94365,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Nuneaton',92698,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('High Peak',92600,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Darlington',92363,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Southport',91703,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chester',90524,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stevenage',90232,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wembley',90045,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Grays',89755,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Harrogate',89060,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hartlepool',88855,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Londonderry County Borough',87153,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cannock',86121,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hemel Hempstead',85629,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('St Albans',84561,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('South Shields',83655,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Derry',83652,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Weston-super-Mare',82903,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Halifax',82624,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Redditch',82253,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Beckenham',82000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Tamworth',81964,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Scunthorpe',79977,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stockton-on-Tees',79957,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wakefield',78978,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Carlisle',78470,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Gateshead',77649,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lisburn',77506,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Fylde',76500,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Paisley',76220,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bracknell',76103,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newcastle under Lyme',75794,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Battersea',75651,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Crewe',75556,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chatham',75509,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hove',75174,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Aylesbury',74748,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('East Kilbride',74740,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Canary Wharf',73390,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rugby',73150,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Salford',72750,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Purley',72000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Guildford',71873,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Shrewsbury',71715,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Peckham',71552,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Barnsley',71447,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lowestoft',70945,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Gosport',70793,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Southall',70000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stafford',69217,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Royal Tunbridge Wells',68910,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ellesmere Port',67768,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rossendale',67400,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Folkestone',66429,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Brixton',66300,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wrexham',65692,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Torquay',65388,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Maidenhead',64831,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kingswood',64793,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Taunton',64621,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Waterlooville',64350,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Macclesfield',63954,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bognor Regis',63885,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newtownabbey',63860,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kettering',63675,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Buckley',63576,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Great Yarmouth',63434,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Runcorn',62872,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ashford',62787,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Tonypandy',62545,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Scarborough',61749,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Widnes',61464,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Aldershot',61339,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bury',61044,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Barking',61000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Castleford',60509,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hereford',60415,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bangor',60385,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stroud',60155,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Margate',60134,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chelsea',60000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Loughborough',59932,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Welwyn Garden City',59910,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Farnborough',59902,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rhondda',59450,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Craigavon',59236,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wallasey',58794,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Littlehampton',58714,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bridgend',58380,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bootle',57791,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Weymouth',57691,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Fareham',57390,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Morley',57385,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cheshunt',57374,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kidderminster',57059,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Corby',56810,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dartford',56694,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Castlereagh',56679,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dewsbury',56640,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Livingston',56570,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stourbridge',56284,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sale',55689,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Halesowen',55265,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Canterbury',55240,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('South Croydon',55198,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Huyton',54738,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Barry',54673,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Gravesend',54263,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Eastleigh',54225,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Acton',53689,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Washington',53526,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Braintree',53477,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hamilton',53200,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Brentwood',52586,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Esher',52392,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Crosby',52140,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Reigate',52123,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dunstable',51973,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Morecambe',51644,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cumbernauld',51610,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Redhill',51559,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Horsham',51472,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Staines',51040,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Batley',50807,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wellingborough',50577,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Clacton-on-Sea',50548,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dunfermline',50380,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bletchley',50193,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Keighley',50171,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hayes',50000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Paignton',49886,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Llanelli',49591,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kirkcaldy',49460,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bromsgrove',49117,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sittingbourne',48948,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('South Benfleet',48824,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Banbury',48651,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('West Bridgford',48314,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Mitcham',48311,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Morden',48233,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cwmbran',48157,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Long Eaton',47898,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Durham',47785,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Northwich',47421,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ayr',47190,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Perth',47180,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lancaster',47162,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Tipton',47000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Inverness',46870,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kilmarnock',46350,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Banstead',46280,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Neath',46126,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('King''s Lynn',46093,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Winchester',46074,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Barrow in Furness',45865,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Yeovil',45784,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Middleton',45589,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Havant',45574,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Carshalton',45525,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hinckley',45249,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Salisbury',44748,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Pontefract',44710,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Coatbridge',43970,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Sutton in Ashfield',43912,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Grantham',43833,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Merthyr Tydfil',43820,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Great Sankey',43793,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Greenock',43690,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ashton-under-Lyne',43675,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Leigh',43626,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Leatherhead',43544,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Letchworth Garden City',43529,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newark on Trent',43363,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Worksop',43252,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bury St Edmunds',42812,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Kirkby',42744,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wallsend',42739,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Redruth',42690,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Welling',42500,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Christchurch',42396,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Andover',42276,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stretford',41953,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dover',41709,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hatfield',41677,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Altrincham',41548,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Coity',41352,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newburn',41347,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Boston',41340,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Holloway',41329,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lytham St Annes',41327,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bridgwater',41276,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Urmston',41198,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wokingham',41143,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Swadlincote',40960,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Trowbridge',40952,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Prescot',40889,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bexhill-on-Sea',40478,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bloxwich',40000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ewell',39994,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('North Shields',39747,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Glenrothes',39100,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Skelmersdale',38944,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Fleet',38726,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Abingdon',38676,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Tonbridge',38657,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ramsgate',38624,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ilkeston',38587,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Coalville',38245,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Canvey Island',38170,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Surbiton',38158,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Whitley Bay',38055,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Greenford',38000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Arnold',37873,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Houghton-Le-Spring',37840,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bishops Stortford',37838,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Leyland',37614,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rushden',37584,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Leighton Buzzard',37469,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Yeadon',37379,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Blyth',37339,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Eccles',37275,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Redcar',37203,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Airdrie',37130,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Peterlee',37015,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Farnham',36971,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chester-le-Street',36917,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Great Malvern',36770,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Herne Bay',36642,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wilmslow',36617,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newton Abbot',36474,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Stirling',36440,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Mangotsfield',36427,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Billericay',36338,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chipping Sodbury',36108,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hitchin',36099,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Walkden',35937,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Tyldesley',35932,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chippenham',35800,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Billingham',35708,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Pontypool',35686,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Accrington',35318,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Falkirk',35310,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Briton Ferry',35179,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hoddesdon',35174,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bridlington',35154,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bentley',34821,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Exmouth',34432,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Yate',34406,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Felling',34355,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Colwyn Bay',34284,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Radcliffe',34239,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Totton',34169,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Letchworth',33955,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chorley',33888,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Bicester',33846,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Haywards Heath',33845,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Irvine',33740,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wigston Magna',33720,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wednesfield',33555,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Strood',33381,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Windsor',33348,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Dumfries',33280,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Glossop',33243,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cramlington',33180,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Pudsey',33109,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ebbw Vale',33068,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Newbury',33065,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wickford',32975,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lichfield',32877,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Brighouse',32872,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Darwen',32566,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wisbech',32489,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Aston',32286,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Borehamwood',32176,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Prestwich',32125,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Motherwell',32120,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Cleethorpes',32017,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Lower Earley',32000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Shirley',32000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Deeside',32000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Falmouth',31988,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Hyde',31926,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Chichester',31654,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Barnstaple',31616,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Spalding',31588,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Rutherglen',31180,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Thornton-Cleveleys',31157,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Aberdare',31135,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Caerphilly',31060,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Ruislip',31000,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Saint Neots',30811,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Burgess Hill',30635,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Beverley',30587,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Deal',30555,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Wishaw',30510,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Pontypridd',30420,0);
INSERT INTO City(city,Population,Number_of_Premier_league_team) VALUES ('Winsford',30259,0);
