CREATE TABLE Play(
   MatchID   INTEGER  NOT NULL REFERENCES Matches(MatchID)
  ,Team_name VARCHAR NOT NULL REFERENCES Team(Name)
  ,PRIMARY KEY(MatchID,Team_name)
);
INSERT INTO Play(MatchID,Team_name) VALUES (1,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (1,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (2,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (2,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (3,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (3,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (4,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (4,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (5,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (5,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (6,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (6,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (7,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (7,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (8,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (8,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (9,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (9,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (10,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (10,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (11,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (11,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (12,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (12,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (13,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (13,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (14,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (14,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (15,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (15,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (16,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (16,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (17,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (17,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (18,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (18,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (19,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (19,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (20,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (20,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (21,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (21,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (22,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (22,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (23,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (23,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (24,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (24,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (25,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (25,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (26,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (26,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (27,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (27,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (28,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (28,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (29,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (29,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (30,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (30,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (31,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (31,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (32,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (32,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (33,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (33,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (34,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (34,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (35,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (35,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (36,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (36,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (37,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (37,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (38,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (38,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (39,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (39,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (40,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (40,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (41,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (41,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (42,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (42,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (43,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (43,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (44,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (44,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (45,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (45,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (46,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (46,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (47,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (47,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (48,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (48,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (49,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (49,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (50,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (50,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (51,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (51,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (52,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (52,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (53,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (53,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (54,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (54,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (55,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (55,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (56,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (56,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (57,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (57,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (58,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (58,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (59,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (59,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (60,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (60,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (61,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (61,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (62,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (62,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (63,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (63,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (64,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (64,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (65,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (65,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (66,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (66,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (67,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (67,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (68,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (68,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (69,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (69,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (70,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (70,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (71,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (71,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (72,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (72,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (73,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (73,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (74,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (74,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (75,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (75,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (76,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (76,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (77,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (77,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (78,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (78,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (79,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (79,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (80,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (80,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (81,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (81,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (82,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (82,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (83,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (83,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (84,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (84,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (85,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (85,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (86,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (86,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (87,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (87,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (88,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (88,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (89,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (89,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (90,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (90,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (91,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (91,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (92,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (92,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (93,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (93,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (94,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (94,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (95,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (95,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (96,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (96,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (97,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (97,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (98,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (98,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (99,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (99,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (100,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (100,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (101,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (101,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (102,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (102,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (103,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (103,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (104,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (104,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (105,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (105,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (106,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (106,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (107,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (107,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (108,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (108,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (109,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (109,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (110,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (110,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (111,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (111,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (112,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (112,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (113,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (113,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (114,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (114,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (115,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (115,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (116,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (116,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (117,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (117,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (118,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (118,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (119,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (119,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (120,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (120,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (121,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (121,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (122,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (122,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (123,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (123,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (124,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (124,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (125,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (125,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (126,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (126,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (127,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (127,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (128,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (128,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (129,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (129,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (130,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (130,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (131,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (131,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (132,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (132,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (133,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (133,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (134,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (134,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (135,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (135,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (136,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (136,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (137,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (137,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (138,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (138,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (139,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (139,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (140,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (140,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (141,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (141,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (142,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (142,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (143,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (143,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (144,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (144,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (145,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (145,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (146,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (146,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (147,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (147,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (148,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (148,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (149,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (149,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (150,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (150,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (151,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (151,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (152,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (152,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (153,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (153,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (154,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (154,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (155,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (155,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (156,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (156,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (157,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (157,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (158,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (158,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (159,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (159,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (160,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (160,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (161,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (161,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (162,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (162,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (163,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (163,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (164,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (164,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (165,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (165,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (166,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (166,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (167,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (167,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (168,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (168,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (169,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (169,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (170,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (170,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (171,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (171,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (172,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (172,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (173,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (173,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (174,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (174,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (175,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (175,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (176,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (176,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (177,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (177,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (178,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (178,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (179,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (179,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (180,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (180,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (181,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (181,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (182,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (182,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (183,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (183,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (184,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (184,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (185,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (185,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (186,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (186,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (187,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (187,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (188,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (188,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (189,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (189,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (190,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (190,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (191,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (191,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (192,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (192,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (193,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (193,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (194,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (194,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (195,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (195,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (196,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (196,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (197,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (197,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (198,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (198,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (199,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (199,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (200,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (200,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (201,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (201,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (202,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (202,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (203,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (203,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (204,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (204,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (205,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (205,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (206,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (206,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (207,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (207,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (208,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (208,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (209,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (209,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (210,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (210,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (211,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (211,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (212,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (212,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (213,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (213,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (214,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (214,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (215,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (215,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (216,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (216,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (217,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (217,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (218,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (218,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (219,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (219,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (220,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (220,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (221,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (221,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (222,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (222,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (223,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (223,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (224,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (224,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (225,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (225,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (226,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (226,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (227,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (227,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (228,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (228,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (229,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (229,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (230,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (230,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (231,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (231,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (232,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (232,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (233,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (233,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (234,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (234,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (235,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (235,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (236,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (236,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (237,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (237,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (238,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (238,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (239,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (239,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (240,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (240,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (241,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (241,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (242,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (242,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (243,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (243,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (244,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (244,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (245,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (245,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (246,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (246,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (247,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (247,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (248,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (248,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (249,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (249,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (250,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (250,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (251,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (251,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (252,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (252,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (253,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (253,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (254,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (254,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (255,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (255,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (256,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (256,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (257,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (257,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (258,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (258,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (259,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (259,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (260,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (260,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (261,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (261,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (262,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (262,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (263,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (263,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (264,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (264,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (265,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (265,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (266,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (266,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (267,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (267,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (268,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (268,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (269,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (269,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (270,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (270,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (271,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (271,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (272,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (272,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (273,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (273,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (274,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (274,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (275,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (275,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (276,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (276,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (277,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (277,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (278,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (278,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (279,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (279,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (280,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (280,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (281,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (281,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (282,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (282,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (283,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (283,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (284,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (284,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (285,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (285,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (286,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (286,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (287,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (287,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (288,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (288,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (289,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (289,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (290,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (290,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (291,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (291,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (292,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (292,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (293,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (293,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (294,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (294,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (295,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (295,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (296,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (296,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (297,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (297,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (298,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (298,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (299,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (299,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (300,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (300,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (301,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (301,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (302,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (302,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (303,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (303,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (304,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (304,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (305,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (305,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (306,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (306,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (307,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (307,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (308,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (308,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (309,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (309,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (310,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (310,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (311,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (311,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (312,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (312,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (313,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (313,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (314,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (314,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (315,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (315,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (316,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (316,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (317,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (317,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (318,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (318,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (319,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (319,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (320,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (320,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (321,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (321,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (322,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (322,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (323,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (323,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (324,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (324,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (325,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (325,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (326,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (326,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (327,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (327,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (328,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (328,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (329,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (329,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (330,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (330,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (331,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (331,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (332,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (332,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (333,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (333,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (334,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (334,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (335,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (335,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (336,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (336,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (337,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (337,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (338,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (338,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (339,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (339,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (340,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (340,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (341,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (341,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (342,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (342,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (343,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (343,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (344,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (344,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (345,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (345,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (346,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (346,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (347,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (347,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (348,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (348,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (349,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (349,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (350,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (350,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (351,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (351,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (352,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (352,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (353,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (353,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (354,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (354,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (355,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (355,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (356,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (356,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (357,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (357,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (358,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (358,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (359,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (359,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (360,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (360,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (361,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (361,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (362,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (362,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (363,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (363,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (364,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (364,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (365,'West Ham');
INSERT INTO Play(MatchID,Team_name) VALUES (365,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (366,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (366,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (367,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (367,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (368,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (368,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (369,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (369,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (370,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (370,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (371,'Brighton');
INSERT INTO Play(MatchID,Team_name) VALUES (371,'Man City');
INSERT INTO Play(MatchID,Team_name) VALUES (372,'Burnley');
INSERT INTO Play(MatchID,Team_name) VALUES (372,'Arsenal');
INSERT INTO Play(MatchID,Team_name) VALUES (373,'Crystal Palace');
INSERT INTO Play(MatchID,Team_name) VALUES (373,'Bournemouth');
INSERT INTO Play(MatchID,Team_name) VALUES (374,'Fulham');
INSERT INTO Play(MatchID,Team_name) VALUES (374,'Newcastle');
INSERT INTO Play(MatchID,Team_name) VALUES (375,'Leicester');
INSERT INTO Play(MatchID,Team_name) VALUES (375,'Chelsea');
INSERT INTO Play(MatchID,Team_name) VALUES (376,'Liverpool');
INSERT INTO Play(MatchID,Team_name) VALUES (376,'Wolves');
INSERT INTO Play(MatchID,Team_name) VALUES (377,'Man United');
INSERT INTO Play(MatchID,Team_name) VALUES (377,'Cardiff');
INSERT INTO Play(MatchID,Team_name) VALUES (378,'Southampton');
INSERT INTO Play(MatchID,Team_name) VALUES (378,'Huddersfield');
INSERT INTO Play(MatchID,Team_name) VALUES (379,'Tottenham');
INSERT INTO Play(MatchID,Team_name) VALUES (379,'Everton');
INSERT INTO Play(MatchID,Team_name) VALUES (380,'Watford');
INSERT INTO Play(MatchID,Team_name) VALUES (380,'West Ham');
