CREATE TABLE Score(
   Home_Team VARCHAR NOT NULL REFERENCES Matches(HomeTeam)
  ,AwayTeam  VARCHAR NOT NULL REFERENCES Matches(AwayTeam)
  ,Score     VARCHAR NOT NULL
  ,PRIMARY KEY(Home_Team,AwayTeam)
);
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Leicester','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Cardiff','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Crystal Palace','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Chelsea','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Tottenham','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Brighton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Everton','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Man City','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','West Ham','4-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Burnley','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Newcastle','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Arsenal','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Southampton','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Wolves','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Fulham','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Bournemouth','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Man United','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Watford','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Huddersfield','6-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Liverpool','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','West Ham','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Everton','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Cardiff','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Brighton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Leicester','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Man City','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Burnley','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Chelsea','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Crystal Palace','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Tottenham','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Fulham','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Bournemouth','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Southampton','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Huddersfield','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Liverpool','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Newcastle','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Wolves','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Man United','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Arsenal','2-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Tottenham','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Leicester','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Cardiff','4-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Crystal Palace','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Fulham','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Arsenal','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Liverpool','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Man United','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','West Ham','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Burnley','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Brighton','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Tottenham','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Bournemouth','4-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Man City','0-5');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Newcastle','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Watford','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Huddersfield','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Southampton','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Wolves','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Everton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Chelsea','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Watford','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Liverpool','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Fulham','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Tottenham','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Brighton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Leicester','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Man United','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Southampton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Burnley','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Crystal Palace','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','West Ham','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Huddersfield','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Wolves','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Everton','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Newcastle','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Cardiff','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Bournemouth','0-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Arsenal','1-5');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Man City','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Chelsea','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Southampton','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Fulham','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Man United','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Liverpool','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Burnley','5-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Brighton','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Tottenham','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Watford','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Crystal Palace','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Leicester','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Wolves','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Bournemouth','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','West Ham','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Cardiff','4-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Newcastle','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Huddersfield','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Chelsea','0-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Arsenal','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Everton','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Man City','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Liverpool','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Man United','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Leicester','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Brighton','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Watford','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Burnley','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Tottenham','2-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Crystal Palace','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Southampton','6-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Fulham','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Brighton','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Tottenham','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','West Ham','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Burnley','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Bournemouth','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Watford','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Wolves','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Everton','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Fulham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Man United','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Leicester','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Cardiff','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Southampton','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Crystal Palace','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Chelsea','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Liverpool','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Man City','0-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Arsenal','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Huddersfield','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Newcastle','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Wolves','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Burnley','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Brighton','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Watford','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Bournemouth','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','West Ham','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Man United','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Tottenham','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Fulham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Everton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Huddersfield','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Crystal Palace','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Man City','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Cardiff','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Liverpool','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Newcastle','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Leicester','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Arsenal','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Southampton','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Chelsea','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Huddersfield','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Liverpool','0-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Brighton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Southampton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Man City','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Tottenham','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Fulham','4-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Crystal Palace','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Wolves','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Watford','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Leicester','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','West Ham','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Newcastle','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Everton','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Burnley','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Cardiff','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Bournemouth','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Chelsea','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Man United','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Arsenal','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Liverpool','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Burnley','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Brighton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Man United','1-5');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Leicester','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Southampton','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Crystal Palace','2-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Fulham','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Watford','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Tottenham','2-6');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Arsenal','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Everton','1-5');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Cardiff','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Wolves','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Man City','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Newcastle','4-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Huddersfield','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Bournemouth','5-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Chelsea','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','West Ham','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Everton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Huddersfield','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Cardiff','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Arsenal','5-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Wolves','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Newcastle','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','West Ham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Chelsea','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Bournemouth','4-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Man City','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Fulham','4-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Tottenham','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Leicester','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Watford','3-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Southampton','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Burnley','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Man United','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Brighton','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Crystal Palace','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Liverpool','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Liverpool','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Fulham','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Huddersfield','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Newcastle','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Watford','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Southampton','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Arsenal','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Bournemouth','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Man United','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Wolves','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Chelsea','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','West Ham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Crystal Palace','4-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Brighton','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Cardiff','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Everton','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Burnley','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Leicester','4-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Tottenham','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Man City','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Cardiff','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Brighton','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Everton','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Burnley','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Man City','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','West Ham','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Chelsea','4-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Leicester','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Crystal Palace','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Watford','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Watford','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Southampton','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Bournemouth','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Huddersfield','5-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Fulham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Wolves','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Newcastle','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Man United','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Arsenal','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Liverpool','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Man City','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Burnley','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','West Ham','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Man United','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Arsenal','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Bournemouth','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Cardiff','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Everton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Chelsea','6-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Leicester','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Newcastle','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Watford','1-5');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Fulham','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Wolves','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Tottenham','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Crystal Palace','1-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Huddersfield','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Southampton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Liverpool','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Everton','0-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Wolves','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Brighton','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Burnley','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Bournemouth','5-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Tottenham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Man United','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Watford','5-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','West Ham','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Fulham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Man City','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Huddersfield','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Crystal Palace','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Southampton','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Arsenal','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Newcastle','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Cardiff','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Liverpool','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Chelsea','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Leicester','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','West Ham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Brighton','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Bournemouth','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Fulham','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Watford','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Everton','3-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Tottenham','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Man United','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Wolves','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Burnley','4-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Newcastle','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Leicester','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Huddersfield','4-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Chelsea','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Liverpool','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Southampton','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Wolves','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Huddersfield','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Man City','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Bournemouth','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Watford','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Everton','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Chelsea','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Tottenham','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Newcastle','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Fulham','4-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Man United','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Brighton','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Cardiff','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Crystal Palace','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Liverpool','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Burnley','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Leicester','1-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Crystal Palace','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Arsenal','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','West Ham','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Newcastle','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Bournemouth','0-5');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Cardiff','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Everton','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','West Ham','2-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Wolves','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Huddersfield','4-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Man City','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Chelsea','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Arsenal','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Cardiff','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Fulham','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Watford','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Tottenham','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Southampton','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Leicester','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Brighton','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Crystal Palace','2-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Liverpool','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Man United','4-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Burnley','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Brighton','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Southampton','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Man City','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Arsenal','3-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Huddersfield','5-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Newcastle','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Everton','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Cardiff','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Bournemouth','3-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','West Ham','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','Wolves','1-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Man City','0-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Arsenal','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Chelsea','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Everton','Burnley','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Bournemouth','Tottenham','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Cardiff','Crystal Palace','2-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Newcastle','Liverpool','2-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('West Ham','Southampton','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Wolves','Fulham','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Arsenal','Brighton','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Chelsea','Watford','3-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Huddersfield','Man United','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man City','Leicester','1-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Brighton','Man City','1-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Burnley','Arsenal','1-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Crystal Palace','Bournemouth','5-3');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Fulham','Newcastle','0-4');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Leicester','Chelsea','0-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Liverpool','Wolves','2-0');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Man United','Cardiff','0-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Southampton','Huddersfield','1-1');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Tottenham','Everton','2-2');
INSERT INTO Score(Home_Team,AwayTeam,Score) VALUES ('Watford','West Ham','1-4');
